 // Source code is unavailable, and was generated by the Fernflower decompiler.
package com.reigninblood.TaleMon_PokeBall;

import com.hypixel.hytale.server.core.modules.interaction.interaction.config.Interaction;
import com.hypixel.hytale.server.core.plugin.JavaPlugin;
import com.hypixel.hytale.server.core.plugin.JavaPluginInit;
import com.reigninblood.TaleMon_PokeBall.interactions.PokeBallCaptureInteraction;
import com.reigninblood.TaleMon_PokeBall.interactions.PokeBallReleaseInteraction;
import javax.annotation.Nonnull;

public class PokeBall_Plugin extends JavaPlugin {
   public PokeBall_Plugin(@Nonnull JavaPluginInit init) {
      super(init);
   }

   protected void setup() {
      this.getCodecRegistry(Interaction.CODEC).register("talemon:pokeball_capture", PokeBallCaptureInteraction.class, PokeBallCaptureInteraction.CODEC);
      this.getCodecRegistry(Interaction.CODEC).register("talemon:pokeball_release", PokeBallReleaseInteraction.class, PokeBallReleaseInteraction.CODEC);
   }
}
