 // Source code is unavailable, and was generated by the Fernflower decompiler.
package com.reigninblood.TaleMon_PokeBall.util;

import java.util.UUID;

final class BestCandidate {
   double score = Double.NEGATIVE_INFINITY;
   UUID uuid = null;
}
