 // Source code is unavailable, and was generated by the Fernflower decompiler.
package com.reigninblood.TaleMon_PokeBall.util;

public record Captured(Integer roleIndex, String npcNameKey) {
   public Integer getRoleIndex() {
      return this.roleIndex;
   }

   public String getNpcNameKey() {
      return this.npcNameKey;
   }
}
