 // Source code is unavailable, and was generated by the Fernflower decompiler.
package com.reigninblood.TaleMon_PokeBall.util;

import com.hypixel.hytale.logger.HytaleLogger;
import com.hypixel.hytale.server.core.entity.entities.Player;
import com.hypixel.hytale.server.core.inventory.Inventory;
import com.hypixel.hytale.server.core.inventory.ItemStack;
import java.util.logging.Level;
import javax.annotation.Nonnull;

public final class ConsumeUtil {
   private ConsumeUtil() {
   }

   public static boolean consumeActiveHotbarItem(@Nonnull Player player, @Nonnull ItemStack expectedHeld) {
      try {
         Inventory inv = player.getInventory();
         byte activeHotbarSlot = inv.getActiveHotbarSlot();
         inv.getHotbar().replaceItemStackInSlot((short)activeHotbarSlot, expectedHeld, ItemStack.EMPTY);
         player.sendInventory();
         return true;
      } catch (Throwable var4) {
         HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] ConsumeUtil: consumeActiveHotbarItem FAILED: %s", String.valueOf(var4));
         return false;
      }
   }
}
