 // Source code is unavailable, and was generated by the Fernflower decompiler.
package com.reigninblood.TaleMon_PokeBall.util;

import com.hypixel.hytale.component.CommandBuffer;
import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.logger.HytaleLogger;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;
import java.lang.reflect.Method;
import java.util.logging.Level;

public final class DespawnUtil {
   private DespawnUtil() {
   }

   public static boolean forceDespawn(CommandBuffer<EntityStore> buffer, Ref<EntityStore> targetRef) {
      Object reason = findAnyRemoveReasonEnumValue();
      if (reason == null) {
         HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] DESPAWN_FAIL: cannot resolve RemoveReason enum value");
         dumpRemoveReasonEnum();
         return false;
      } else if (invoke(buffer, "tryRemoveEntity", targetRef, reason)) {
         HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] DESPAWN_OK via=tryRemoveEntity(ref,RemoveReason=%s)", reason.toString());
         return true;
      } else if (invoke(buffer, "removeEntity", targetRef, reason)) {
         HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] DESPAWN_OK via=removeEntity(ref,RemoveReason=%s)", reason.toString());
         return true;
      } else {
         HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] DESPAWN_FAIL: removeEntity/tryRemoveEntity invocation failed (reason=%s)", reason.toString());
         dumpBufferRemoveSignatures(buffer);
         return false;
      }
   }

   private static boolean invoke(Object obj, String methodName, Object arg0, Object arg1) {
      try {
         Method[] var4 = obj.getClass().getMethods();
         int var5 = var4.length;

         for(int var6 = 0; var6 < var5; ++var6) {
            Method m = var4[var6];
            if (m.getName().equals(methodName) && m.getParameterCount() == 2) {
               Class<?> p0 = m.getParameterTypes()[0];
               Class<?> p1 = m.getParameterTypes()[1];
               if (p0.isAssignableFrom(arg0.getClass()) && p1.isAssignableFrom(arg1.getClass())) {
                  m.invoke(obj, arg0, arg1);
                  return true;
               }
            }
         }

         return false;
      } catch (Throwable var10) {
         return false;
      }
   }

   private static Object findAnyRemoveReasonEnumValue() {
      try {
         Class<?> enumCls = Class.forName("com.hypixel.hytale.component.RemoveReason");
         if (!enumCls.isEnum()) {
            return null;
         } else {
            Object[] values = enumCls.getEnumConstants();
            return values != null && values.length != 0 ? values[0] : null;
         }
      } catch (Throwable var2) {
         return null;
      }
   }

   private static void dumpRemoveReasonEnum() {
      try {
         Class<?> enumCls = Class.forName("com.hypixel.hytale.component.RemoveReason");
         if (!enumCls.isEnum()) {
            HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] RemoveReason is not enum?? cls=%s", enumCls.getName());
            return;
         }

         Object[] values = enumCls.getEnumConstants();
         HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] RemoveReason values:");
         if (values != null) {
            Object[] var2 = values;
            int var3 = values.length;

            for(int var4 = 0; var4 < var3; ++var4) {
               Object v = var2[var4];
               HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall]   %s", v.toString());
            }
         }
      } catch (Throwable var6) {
         HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] RemoveReason dump failed: %s", var6.toString());
      }

   }

   private static void dumpBufferRemoveSignatures(Object buffer) {
      Method[] var1 = buffer.getClass().getMethods();
      int var2 = var1.length;

      for(int var3 = 0; var3 < var2; ++var3) {
         Method m = var1[var3];
         String n = m.getName();
         if (n.equals("removeEntity") || n.equals("tryRemoveEntity")) {
            Class<?>[] p = m.getParameterTypes();
            HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] buffer.%s(%s,%s) -> %s", n, p.length > 0 ? p[0].getName() : "", p.length > 1 ? p[1].getName() : "", m.getReturnType().getName());
         }
      }

   }
}
