 // Source code is unavailable, and was generated by the Fernflower decompiler.
package com.reigninblood.TaleMon_PokeBall.util;

import com.hypixel.hytale.logger.HytaleLogger;
import com.hypixel.hytale.server.core.entity.entities.Player;
import com.hypixel.hytale.server.core.inventory.Inventory;
import com.hypixel.hytale.server.core.inventory.ItemStack;
import java.lang.reflect.Method;
import java.util.logging.Level;

public final class GiveUtil {
   private GiveUtil() {
   }

   public static boolean giveToStorage(Player player, ItemStack stack) {
      try {
         if (player != null && stack != null && stack != ItemStack.EMPTY) {
            Inventory inv = player.getInventory();
            if (inv == null) {
               return false;
            } else {
               int[] sectionIds = new int[]{-2, 2, 1, 0, 3, 4, 5};
               int[] var4 = sectionIds;
               int var5 = sectionIds.length;

               for(int var6 = 0; var6 < var5; ++var6) {
                  int sectionId = var4[var6];
                  Object container = null;

                  try {
                     Method getSectionById = inv.getClass().getMethod("getSectionById", Integer.TYPE);
                     container = getSectionById.invoke(inv, sectionId);
                  } catch (Throwable var11) {
                  }

                  if (container != null) {
                     boolean ok = tryInsertIntoContainer(container, stack);
                     if (ok) {
                        HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] GiveUtil: OK section=%s item=%s x%s container=%s", sectionId, stack.getItemId(), stack.getQuantity(), container.getClass().getName());
                        player.sendInventory();
                        return true;
                     }
                  }
               }

               try {
                  Method putAll = inv.getClass().getMethod("putAll", Integer.TYPE);
                  Object tx = putAll.invoke(inv, 0);
                  HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] GiveUtil: fallback putAll(0) tx=%s", String.valueOf(tx));
               } catch (Throwable var10) {
               }

               HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] GiveUtil: FAILED: no container accepted the item");
               return false;
            }
         } else {
            return false;
         }
      } catch (Throwable var12) {
         HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] GiveUtil: FAILED: %s", String.valueOf(var12));
         return false;
      }
   }

   private static boolean tryInsertIntoContainer(Object container, ItemStack stack) {
      String[] methodNames = new String[]{"addItemStack", "tryAddItemStack", "insertItemStack", "add", "tryAdd", "offer", "put"};
      String[] var3 = methodNames;
      int var4 = methodNames.length;

      for(int var5 = 0; var5 < var4; ++var5) {
         String name = var3[var5];
         Method[] var7 = container.getClass().getMethods();
         int var8 = var7.length;

         for(int var9 = 0; var9 < var8; ++var9) {
            Method m = var7[var9];
            if (m.getName().equals(name)) {
               Class[] p = m.getParameterTypes();

               try {
                  if (p.length == 1 && p[0] == ItemStack.class) {
                     Object r = m.invoke(container, stack);
                     if (r instanceof Boolean) {
                        Boolean b = (Boolean)r;
                        return b;
                     }

                     return r != null;
                  }
               } catch (Throwable var14) {
               }
            }
         }
      }

      return false;
   }
}
