 // Source code is unavailable, and was generated by the Fernflower decompiler.
package com.reigninblood.TaleMon_PokeBall.util;

import com.hypixel.hytale.logger.HytaleLogger;
import com.hypixel.hytale.server.core.entity.entities.Player;
import com.hypixel.hytale.server.core.inventory.ItemStack;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.logging.Level;

public final class InventoryUtil {
   private InventoryUtil() {
   }

   public static boolean decrementHeldItem(Player player, String expectedId) {
      try {
         ItemStack held = getHeldItem(player);
         if (held == null) {
            HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] InventoryUtil: held item is null");
            return false;
         } else {
            String itemId = getItemId(held);
            int qty = getQuantity(held);
            if (itemId != null && itemId.equals(expectedId)) {
               if (qty <= 0) {
                  return false;
               } else {
                  ItemStack newHeld = new ItemStack(itemId, qty - 1);
                  copyDurabilityIfPossible(held, newHeld);
                  return setHeldItem(player, newHeld);
               }
            } else {
               HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] InventoryUtil: held item mismatch id=%s expected=%s", String.valueOf(itemId), expectedId);
               return false;
            }
         }
      } catch (Throwable var6) {
         HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] InventoryUtil: decrementHeldItem ERROR %s", var6.toString());
         dumpPlayerInventoryMethods(player);
         return false;
      }
   }

   public static boolean addToInventory(Player player, ItemStack stack) {
      try {
         Object inv = getInventoryObject(player);
         if (inv == null) {
            HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] InventoryUtil: inventory object is null");
            return false;
         } else {
            String[] names = new String[]{"addItem", "add", "give", "tryAdd", "addToInventory", "tryAddItem"};
            String[] var4 = names;
            int var5 = names.length;

            for(int var6 = 0; var6 < var5; ++var6) {
               String name = var4[var6];
               Method ok = findMethod(inv.getClass(), name, ItemStack.class);
               if (ok != null) {
                  Object r = ok.invoke(inv, stack);
                  if (r instanceof Boolean) {
                     return (Boolean)r;
                  }

                  return true;
               }
            }

            Method give = findMethod(player.getClass(), "giveItem", ItemStack.class);
            if (give != null) {
               Object r = give.invoke(player, stack);
               if (r instanceof Boolean) {
                  return (Boolean)r;
               } else {
                  return true;
               }
            } else {
               HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] InventoryUtil: no add method found on inventory/player");
               dumpInventoryMethods(inv);
               return false;
            }
         }
      } catch (Throwable var10) {
         HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] InventoryUtil: addToInventory ERROR %s", var10.toString());
         return false;
      }
   }

   private static ItemStack getHeldItem(Player player) {
      try {
         Method m = findAnyNoArgMethod(player.getClass(), "getHeldItem", "getActiveItem", "getMainHandItem", "getWieldedItem");
         if (m != null) {
            Object r = m.invoke(player);
            return r instanceof ItemStack ? (ItemStack)r : null;
         }
      } catch (Throwable var3) {
      }

      return null;
   }

   private static boolean setHeldItem(Player player, ItemStack newStack) {
      try {
         Method m = findMethod(player.getClass(), "setHeldItem", ItemStack.class);
         if (m != null) {
            m.invoke(player, newStack);
            return true;
         } else {
            Method alt = findAnyOneArgMethod(player.getClass(), ItemStack.class, "setActiveItem", "setMainHandItem", "setWieldedItem");
            if (alt != null) {
               alt.invoke(player, newStack);
               return true;
            } else {
               HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] InventoryUtil: cannot set held item (no setter found)");
               dumpPlayerInventoryMethods(player);
               return false;
            }
         }
      } catch (Throwable var4) {
         return false;
      }
   }

   private static Object getInventoryObject(Player player) {
      try {
         Method m = findAnyNoArgMethod(player.getClass(), "getInventory", "inventory", "getPlayerInventory");
         if (m != null) {
            return m.invoke(player);
         }
      } catch (Throwable var2) {
      }

      return null;
   }

   private static String getItemId(ItemStack stack) {
      Object r;
      try {
         Method m = stack.getClass().getMethod("getItemId");
         r = m.invoke(stack);
         return r instanceof String ? (String)r : null;
      } catch (Throwable var4) {
         try {
            Field f = stack.getClass().getDeclaredField("itemId");
            f.setAccessible(true);
            r = f.get(stack);
            return r instanceof String ? (String)r : null;
         } catch (Throwable var3) {
            return null;
         }
      }
   }

   private static int getQuantity(ItemStack stack) {
      Object r;
      try {
         Method m = stack.getClass().getMethod("getQuantity");
         r = m.invoke(stack);
         return r instanceof Integer ? (Integer)r : 0;
      } catch (Throwable var4) {
         try {
            Field f = stack.getClass().getDeclaredField("quantity");
            f.setAccessible(true);
            r = f.get(stack);
            return r instanceof Integer ? (Integer)r : 0;
         } catch (Throwable var3) {
            return 0;
         }
      }
   }

   private static void copyDurabilityIfPossible(ItemStack from, ItemStack to) {
      try {
         Method gm = from.getClass().getMethod("getDurability");
         Method sm = to.getClass().getMethod("setDurability", Double.TYPE);
         Object d = gm.invoke(from);
         if (d instanceof Double) {
            sm.invoke(to, (Double)d);
         }
      } catch (Throwable var5) {
      }

   }

   private static Method findMethod(Class<?> c, String name, Class<?>... params) {
      try {
         return c.getMethod(name, params);
      } catch (Throwable var4) {
         return null;
      }
   }

   private static Method findAnyNoArgMethod(Class<?> c, String... names) {
      String[] var2 = names;
      int var3 = names.length;
      int var4 = 0;

      while(var4 < var3) {
         String n = var2[var4];

         try {
            return c.getMethod(n);
         } catch (Throwable var7) {
            ++var4;
         }
      }

      return null;
   }

   private static Method findAnyOneArgMethod(Class<?> c, Class<?> param, String... names) {
      String[] var3 = names;
      int var4 = names.length;
      int var5 = 0;

      while(var5 < var4) {
         String n = var3[var5];

         try {
            return c.getMethod(n, param);
         } catch (Throwable var8) {
            ++var5;
         }
      }

      return null;
   }

   private static void dumpInventoryMethods(Object inv) {
      HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] InventoryUtil: inventory class=%s methods:", inv.getClass().getName());
      Method[] var1 = inv.getClass().getMethods();
      int var2 = var1.length;

      for(int var3 = 0; var3 < var2; ++var3) {
         Method m = var1[var3];
         String n = m.getName().toLowerCase();
         if (n.contains("add") || n.contains("give") || n.contains("insert") || n.contains("put")) {
            HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall]   %s(%d) -> %s", m.getName(), m.getParameterCount(), m.getReturnType().getName());
         }
      }

   }

   private static void dumpPlayerInventoryMethods(Player player) {
      HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] InventoryUtil: Player methods containing held/inventory:");
      Method[] var1 = player.getClass().getMethods();
      int var2 = var1.length;

      for(int var3 = 0; var3 < var2; ++var3) {
         Method m = var1[var3];
         String n = m.getName().toLowerCase();
         if (n.contains("inventory") || n.contains("held") || n.contains("hand") || n.contains("active") || n.contains("wield")) {
            HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall]   %s(%d) -> %s", m.getName(), m.getParameterCount(), m.getReturnType().getName());
         }
      }

   }
}
