 // Source code is unavailable, and was generated by the Fernflower decompiler.
package com.reigninblood.TaleMon_PokeBall.util;

import com.hypixel.hytale.logger.HytaleLogger;
import com.hypixel.hytale.server.core.inventory.ItemStack;
import java.lang.reflect.Method;
import java.util.logging.Level;
import org.bson.BsonDocument;
import org.bson.BsonInt32;
import org.bson.BsonString;

public final class MetaUtil {
   private MetaUtil() {
   }

   public static ItemStack withCapturedEntity(ItemStack stack, int roleIndex, String npcNameKey, String iconPath, String fullItemIcon) {
      try {
         BsonDocument captured = new BsonDocument();
         captured.put("RoleIndex", new BsonInt32(roleIndex));
         if (npcNameKey != null) {
            captured.put("NpcNameKey", new BsonString(npcNameKey));
         }

         if (iconPath != null) {
            captured.put("IconPath", new BsonString(iconPath));
         }

         if (fullItemIcon != null) {
            captured.put("FullItemIcon", new BsonString(fullItemIcon));
         }

         BsonDocument meta = new BsonDocument();
         meta.put("CapturedEntity", captured);
         ItemStack out = tryWithMetadata(stack, meta);
         if (out == null) {
            HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] MetaUtil: withMetadata(...) not found / failed");
            dumpWithMetadataMethods(stack);
            return stack;
         } else {
            try {
               Object md = stack.getClass().getMethod("getMetadata").invoke(out);
               HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] MetaUtil: metadata after set = %s", String.valueOf(md));
            } catch (Throwable var9) {
            }

            return out;
         }
      } catch (Throwable var10) {
         HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] MetaUtil ERROR: %s", var10.toString());
         return stack;
      }
   }

   private static ItemStack tryWithMetadata(ItemStack stack, BsonDocument meta) {
      try {
         Method[] var2 = stack.getClass().getMethods();
         int var3 = var2.length;

         for(int var4 = 0; var4 < var3; ++var4) {
            Method m = var2[var4];
            if (m.getName().equals("withMetadata")) {
               int pc = m.getParameterCount();
               Class<?>[] p = m.getParameterTypes();
               Object r;
               if (pc == 1 && BsonDocument.class.isAssignableFrom(p[0])) {
                  r = m.invoke(stack, meta);
                  return r instanceof ItemStack ? (ItemStack)r : null;
               }

               if (pc == 2 && p[0] == String.class) {
                  r = m.invoke(stack, "CapturedEntity", meta.get("CapturedEntity"));
                  return r instanceof ItemStack ? (ItemStack)r : null;
               }
            }
         }

         return null;
      } catch (Throwable var9) {
         return null;
      }
   }

   private static void dumpWithMetadataMethods(ItemStack stack) {
      HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] MetaUtil: available withMetadata overloads:");
      Method[] var1 = stack.getClass().getMethods();
      int var2 = var1.length;

      for(int var3 = 0; var3 < var2; ++var3) {
         Method m = var1[var3];
         if (m.getName().equals("withMetadata")) {
            HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall]   withMetadata(%d) -> %s", m.getParameterCount(), m.getReturnType().getName());
         }
      }

   }
}
