 // Source code is unavailable, and was generated by the Fernflower decompiler.
package com.reigninblood.TaleMon_PokeBall.util;

import org.bson.BsonDocument;
import org.bson.BsonValue;

public final class MetaReadUtil {
   private MetaReadUtil() {
   }

   public static com.reigninblood.TaleMon_PokeBall.util.MetaReadUtil.Captured readCapturedEntity(BsonDocument meta) {
      if (meta == null) {
         return null;
      } else {
         BsonValue ce = meta.get("CapturedEntity");
         if (ce != null && ce.isDocument()) {
            BsonDocument d = ce.asDocument();
            Integer roleIndex = null;
            String npcNameKey = null;
            BsonValue ri = d.get("RoleIndex");
            if (ri != null && ri.isInt32()) {
               roleIndex = ri.asInt32().getValue();
            }

            BsonValue nk = d.get("NpcNameKey");
            if (nk != null && nk.isString()) {
               npcNameKey = nk.asString().getValue();
            }

            return roleIndex == null && npcNameKey == null ? null : new com.reigninblood.TaleMon_PokeBall.util.MetaReadUtil.Captured(roleIndex, npcNameKey);
         } else {
            return null;
         }
      }
   }
}
