 // Source code is unavailable, and was generated by the Fernflower decompiler.
package com.reigninblood.TaleMon_PokeBall.util;

public record MetaReadUtil$Captured(Integer roleIndex, String npcNameKey) {
   public MetaReadUtil$Captured(Integer roleIndex, String npcNameKey) {
      this.roleIndex = roleIndex;
      this.npcNameKey = npcNameKey;
   }

   public Integer roleIndex() {
      return this.roleIndex;
   }

   public String npcNameKey() {
      return this.npcNameKey;
   }
}
