 // Source code is unavailable, and was generated by the Fernflower decompiler.
package com.reigninblood.TaleMon_PokeBall.util;

import com.hypixel.hytale.builtin.tagset.config.NPCGroup;
import com.hypixel.hytale.logger.HytaleLogger;
import java.lang.reflect.Method;
import java.util.logging.Level;
import javax.annotation.Nonnull;

public final class PokemonGroupUtil {
   private static final String GROUP_ID = "Pokemon";
   private static volatile String[] cachedInclude = null;

   private PokemonGroupUtil() {
   }

   public static boolean isPokemonRole(@Nonnull String roleName) {
      String[] list = getIncludedRoles();
      if (list != null && list.length != 0) {
         String[] var2 = list;
         int var3 = list.length;

         for(int var4 = 0; var4 < var3; ++var4) {
            String s = var2[var4];
            if (roleName.equals(s)) {
               return true;
            }
         }

         return false;
      } else {
         return false;
      }
   }

   public static void reload() {
      cachedInclude = null;
   }

   private static String[] getIncludedRoles() {
      if (cachedInclude != null) {
         return cachedInclude;
      } else {
         NPCGroup group = loadGroupById("Pokemon");
         if (group == null) {
            HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] PokemonGroupUtil: group '%s' not found (Pokemon.json not loaded?)", "Pokemon");
            cachedInclude = new String[0];
            return cachedInclude;
         } else {
            String[] roles = group.getIncludedTags();
            cachedInclude = roles != null ? roles : new String[0];
            HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] PokemonGroupUtil: loaded %s pokemon roles from group '%s'", cachedInclude.length, "Pokemon");
            return cachedInclude;
         }
      }
   }

   private static NPCGroup loadGroupById(@Nonnull String id) {
      try {
         Object assetMap = NPCGroup.getAssetMap();
         if (assetMap == null) {
            return null;
         } else {
            NPCGroup g = tryCall(assetMap, "get", id);
            if (g != null) {
               return g;
            } else {
               g = tryCall(assetMap, "getOrNull", id);
               if (g != null) {
                  return g;
               } else {
                  g = tryCall(assetMap, "getByKey", id);
                  if (g != null) {
                     return g;
                  } else {
                     g = tryCall(assetMap, "find", id);
                     if (g != null) {
                        return g;
                     } else {
                        dumpAssetMapMethods(assetMap);
                        return null;
                     }
                  }
               }
            }
         }
      } catch (Throwable var3) {
         HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] PokemonGroupUtil: loadGroupById failed: %s", String.valueOf(var3));
         return null;
      }
   }

   private static NPCGroup tryCall(Object target, String methodName, String id) {
      try {
         Method m = target.getClass().getMethod(methodName, String.class);
         Object r = m.invoke(target, id);
         return r instanceof NPCGroup ? (NPCGroup)r : null;
      } catch (Throwable var5) {
         return null;
      }
   }

   private static void dumpAssetMapMethods(Object assetMap) {
      try {
         HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] PokemonGroupUtil: AssetMap class=%s", assetMap.getClass().getName());
         Method[] var1 = assetMap.getClass().getMethods();
         int var2 = var1.length;

         for(int var3 = 0; var3 < var2; ++var3) {
            Method m = var1[var3];
            if (m.getParameterCount() == 1 && m.getParameterTypes()[0] == String.class) {
               HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] PokemonGroupUtil: AssetMap method candidate: %s(%s) -> %s", m.getName(), m.getParameterTypes()[0].getName(), m.getReturnType().getName());
            }
         }
      } catch (Throwable var5) {
      }

   }
}
