 // Source code is unavailable, and was generated by the Fernflower decompiler.
package com.reigninblood.TaleMon_PokeBall.util;

import com.hypixel.hytale.math.vector.Vector3d;

public final class SpawnPosUtil {
   private static final double SAFE_Y_OFFSET = 1.6D;

   private SpawnPosUtil() {
   }

   public static Vector3d makeSafe(Vector3d raw) {
      if (raw == null) {
         return null;
      } else {
         double bx = Math.floor(raw.x);
         double by = Math.floor(raw.y);
         double bz = Math.floor(raw.z);
         return new Vector3d(bx + 0.5D, by + 1.6D, bz + 0.5D);
      }
   }

   public static Vector3d makeSafe(Vector3d raw, double extraY) {
      Vector3d base = makeSafe(raw);
      return base == null ? null : new Vector3d(base.x, base.y + extraY, base.z);
   }
}
