 // Source code is unavailable, and was generated by the Fernflower decompiler.
package com.reigninblood.TaleMon_PokeBall.util;

import java.util.UUID;

class TargetingUtil$BestCandidate {
   double score = 0.0D;
   UUID uuid = null;

   private TargetingUtil$BestCandidate() {
   }
}
