 // Source code is unavailable, and was generated by the Fernflower decompiler.
package com.reigninblood.TaleMon_PokeBall.util;

import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.component.Store;
import com.hypixel.hytale.component.query.Query;
import com.hypixel.hytale.math.vector.Vector3d;
import com.hypixel.hytale.math.vector.Vector3f;
import com.hypixel.hytale.server.core.modules.entity.component.HeadRotation;
import com.hypixel.hytale.server.core.modules.entity.component.TransformComponent;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;
import com.hypixel.hytale.server.npc.entities.NPCEntity;
import java.util.UUID;

public final class TargetingUtil {
   private static final double MAX_DISTANCE = 6.0D;
   private static final double MIN_DOT = 0.7D;

   private TargetingUtil() {
   }

   public static UUID findTargetNpcUuid(Store<EntityStore> store, Ref<EntityStore> playerRef) {
      if (store != null && playerRef != null && playerRef.isValid()) {
         TransformComponent playerTransform = (TransformComponent)store.getComponent(playerRef, TransformComponent.getComponentType());
         if (playerTransform == null) {
            return null;
         } else {
            Vector3d playerPos = new Vector3d(playerTransform.getPosition());
            Vector3f rotation = new Vector3f(playerTransform.getRotation());
            HeadRotation headRotation = (HeadRotation)store.getComponent(playerRef, HeadRotation.getComponentType());
            Vector3f headRot = headRotation != null ? headRotation.getRotation() : rotation;
            Vector3f forward = new Vector3f(Vector3f.FORWARD);
            forward.rotateY(headRot.getYaw());
            forward.rotateX(headRot.getPitch());
            forward.normalize();
            Vector3d forwardDir = new Vector3d((double)forward.x, (double)forward.y, (double)forward.z);
            com.reigninblood.TaleMon_PokeBall.util.TargetingUtil.BestCandidate best = new com.reigninblood.TaleMon_PokeBall.util.TargetingUtil.BestCandidate();
            store.forEachChunk(Query.any(), (chunk, buffer) -> {
               int size = chunk.size();

               for(int i = 0; i < size; ++i) {
                  NPCEntity npc = (NPCEntity)chunk.getComponent(i, NPCEntity.getComponentType());
                  if (npc != null) {
                     TransformComponent npcTransform = (TransformComponent)chunk.getComponent(i, TransformComponent.getComponentType());
                     if (npcTransform != null) {
                        Vector3d toNpc = (new Vector3d(npcTransform.getPosition())).subtract(playerPos);
                        double dist = toNpc.length();
                        if (!(dist <= 0.1D) && !(dist > 6.0D)) {
                           Vector3d dir = (new Vector3d(toNpc)).normalize();
                           double dot = forwardDir.dot(dir);
                           if (!(dot < 0.7D)) {
                              double score = dot / dist;
                              if (score > best.score) {
                                 best.score = score;
                                 best.uuid = npc.getUuid();
                              }
                           }
                        }
                     }
                  }
               }

            });
            return best.uuid;
         }
      } else {
         return null;
      }
   }
}
