 // Source code is unavailable, and was generated by the Fernflower decompiler.
package com.reigninblood.TaleMon_PokeBall.interactions;

import com.hypixel.hytale.codec.builder.BuilderCodec;
import com.hypixel.hytale.codec.builder.BuilderCodec.Builder;
import com.hypixel.hytale.component.CommandBuffer;
import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.logger.HytaleLogger;
import com.hypixel.hytale.protocol.InteractionState;
import com.hypixel.hytale.protocol.InteractionType;
import com.hypixel.hytale.server.core.entity.InteractionContext;
import com.hypixel.hytale.server.core.entity.entities.Player;
import com.hypixel.hytale.server.core.inventory.ItemStack;
import com.hypixel.hytale.server.core.modules.interaction.interaction.CooldownHandler;
import com.hypixel.hytale.server.core.modules.interaction.interaction.config.SimpleInstantInteraction;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;
import com.hypixel.hytale.server.npc.entities.NPCEntity;
import com.reigninblood.TaleMon_PokeBall.util.DespawnUtil;
import com.reigninblood.TaleMon_PokeBall.util.GiveUtil;
import com.reigninblood.TaleMon_PokeBall.util.MetaUtil;
import com.reigninblood.TaleMon_PokeBall.util.PokemonList;
import java.lang.reflect.Field;
import java.util.logging.Level;
import javax.annotation.Nonnull;

public class PokeBallCaptureInteraction extends SimpleInstantInteraction {
   public static final String ID = "talemon:pokeball_capture";
   public static final BuilderCodec<PokeBallCaptureInteraction> CODEC;

   public PokeBallCaptureInteraction(String id) {
      super(id);
   }

   protected PokeBallCaptureInteraction() {
      super("talemon:pokeball_capture");
   }

   protected void firstRun(@Nonnull InteractionType type, @Nonnull InteractionContext context, @Nonnull CooldownHandler cooldownHandler) {
      Ref<EntityStore> playerRef = context.getEntity();
      Ref<EntityStore> targetRef = context.getTargetEntity();
      CommandBuffer<EntityStore> buffer = context.getCommandBuffer();
      if (buffer == null) {
         context.getState().state = InteractionState.Failed;
      } else {
         Player player = (Player)buffer.getComponent(playerRef, Player.getComponentType());
         if (player != null && targetRef != null) {
            NPCEntity npc = (NPCEntity)buffer.getComponent(targetRef, NPCEntity.getComponentType());
            if (npc == null) {
               context.getState().state = InteractionState.Failed;
            } else {
               Object role = npc.getRole();
               Integer roleIndexValue = readIntByMethodOrField(role, new String[]{"getRoleIndex", "roleIndex", "getRoleId", "getIndex"}, new String[]{"roleIndex", "roleId", "index"});
               int roleIndex = roleIndexValue != null ? roleIndexValue : -1;
               String roleName = readStringByMethodOrField(role, new String[]{"getRoleName", "roleName", "getName", "name"}, new String[]{"roleName", "name"});
               if (roleName == null || roleName.isEmpty()) {
                  roleName = "Unknown";
               }

               if (!PokemonList.isPokemon(roleName)) {
                  HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] CAPTURE_BLOCKED not a Pokemon: roleName=%s roleIndex=%s", roleName, roleIndex);
                  context.getState().state = InteractionState.Failed;
               } else {
                  HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] CAPTURE_OK roleName=%s roleIndex=%s target=%s", roleName, roleIndex, targetRef);
                  String pokemonBallItemId = makePokemonFullBallItemId(roleName);
                  HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] CAPTURE giveItemId=%s (fallback=PokeBall_Full)", pokemonBallItemId);
                  ItemStack fullBall = new ItemStack(pokemonBallItemId, 1);
                  ItemStack fullBallWithMeta = MetaUtil.withCapturedEntity(fullBall, roleIndex, roleName, (String)null, (String)null);
                  boolean given = GiveUtil.giveToStorage(player, fullBallWithMeta);
                  if (!given) {
                     HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] GIVE failed for %s -> fallback to PokeBall_Full", pokemonBallItemId);
                     ItemStack fallbackBall = new ItemStack("PokeBall_Full", 1);
                     ItemStack fallbackWithMeta = MetaUtil.withCapturedEntity(fallbackBall, roleIndex, roleName, (String)null, (String)null);
                     given = GiveUtil.giveToStorage(player, fallbackWithMeta);
                  }

                  HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] GIVE fullBallWithMeta ok=%s", given);
                  if (!given) {
                     context.getState().state = InteractionState.Failed;
                  } else {
                     boolean despawnOk = DespawnUtil.forceDespawn(buffer, targetRef);
                     HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] DESPAWN result=%s", despawnOk);
                     context.getState().state = InteractionState.Finished;
                  }
               }
            }
         } else {
            context.getState().state = InteractionState.Failed;
         }
      }
   }

   private static Integer readIntByMethodOrField(Object source, String[] methods, String[] fields) {
      if (source == null) {
         return null;
      }

      int var3 = methods.length;

      for(int var4 = 0; var4 < var3; ++var4) {
         String methodName = methods[var4];

         try {
            Object value = source.getClass().getMethod(methodName).invoke(source);
            if (value instanceof Integer) {
               return (Integer)value;
            }

            if (value instanceof Number) {
               return ((Number)value).intValue();
            }
         } catch (Throwable var10) {
         }
      }

      var3 = fields.length;

      for(int var11 = 0; var11 < var3; ++var11) {
         String fieldName = fields[var11];

         try {
            Field field = source.getClass().getDeclaredField(fieldName);
            field.setAccessible(true);
            Object value = field.get(source);
            if (value instanceof Integer) {
               return (Integer)value;
            }

            if (value instanceof Number) {
               return ((Number)value).intValue();
            }
         } catch (Throwable var9) {
         }
      }

      return null;
   }

   private static String readStringByMethodOrField(Object source, String[] methods, String[] fields) {
      if (source == null) {
         return null;
      }

      int var3 = methods.length;

      for(int var4 = 0; var4 < var3; ++var4) {
         String methodName = methods[var4];

         try {
            Object value = source.getClass().getMethod(methodName).invoke(source);
            if (value instanceof String) {
               return (String)value;
            }
         } catch (Throwable var9) {
         }
      }

      var3 = fields.length;

      for(int var10 = 0; var10 < var3; ++var10) {
         String fieldName = fields[var10];

         try {
            Field field = source.getClass().getDeclaredField(fieldName);
            field.setAccessible(true);
            Object value = field.get(source);
            if (value instanceof String) {
               return (String)value;
            }
         } catch (Throwable var8) {
         }
      }

      return null;
   }

   private static String makePokemonFullBallItemId(String roleName) {
      if (roleName != null && !roleName.isEmpty()) {
         String safe = roleName.replaceAll("[^A-Za-z0-9_]", "_");
         safe = safe.replaceAll("_+", "_");
         return "PokeBall_" + safe;
      } else {
         return "PokeBall_Full";
      }
   }

   static {
      CODEC = ((Builder)BuilderCodec.builder(PokeBallCaptureInteraction.class, PokeBallCaptureInteraction::new, SimpleInstantInteraction.CODEC).documentation("Capture a NPC into a Pok\u00e9Ball (Pokemon only)")).build();
   }
}
