 // Source code is unavailable, and was generated by the Fernflower decompiler.
package com.reigninblood.TaleMon_PokeBall.interactions;

import com.hypixel.hytale.codec.builder.BuilderCodec;
import com.hypixel.hytale.codec.builder.BuilderCodec.Builder;
import com.hypixel.hytale.component.CommandBuffer;
import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.component.Store;
import com.hypixel.hytale.function.consumer.TriConsumer;
import com.hypixel.hytale.logger.HytaleLogger;
import com.hypixel.hytale.math.vector.Vector3d;
import com.hypixel.hytale.math.vector.Vector3f;
import com.hypixel.hytale.protocol.BlockPosition;
import com.hypixel.hytale.protocol.InteractionState;
import com.hypixel.hytale.protocol.InteractionType;
import com.hypixel.hytale.server.core.asset.type.blocktype.config.BlockFace;
import com.hypixel.hytale.server.core.asset.type.model.config.Model;
import com.hypixel.hytale.server.core.entity.Entity;
import com.hypixel.hytale.server.core.entity.EntityUtils;
import com.hypixel.hytale.server.core.entity.InteractionContext;
import com.hypixel.hytale.server.core.entity.LivingEntity;
import com.hypixel.hytale.server.core.entity.entities.Player;
import com.hypixel.hytale.server.core.inventory.ItemStack;
import com.hypixel.hytale.server.core.modules.interaction.interaction.CooldownHandler;
import com.hypixel.hytale.server.core.modules.interaction.interaction.config.SimpleInstantInteraction;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;
import com.hypixel.hytale.server.npc.NPCPlugin;
import com.hypixel.hytale.server.npc.metadata.CapturedNPCMetadata;
import com.reigninblood.TaleMon_PokeBall.util.ConsumeUtil;
import com.reigninblood.TaleMon_PokeBall.util.MetaReadUtil;
import com.reigninblood.TaleMon_PokeBall.util.SpawnPosUtil;
import java.lang.reflect.Method;
import java.util.logging.Level;
import javax.annotation.Nonnull;

public class PokeBallReleaseInteraction extends SimpleInstantInteraction {
   public static final String ID = "talemon:pokeball_release";
   public static final BuilderCodec<PokeBallReleaseInteraction> CODEC;

   public PokeBallReleaseInteraction(String id) {
      super(id);
   }

   protected PokeBallReleaseInteraction() {
      super("talemon:pokeball_release");
   }

   protected void firstRun(@Nonnull InteractionType type, @Nonnull InteractionContext context, @Nonnull CooldownHandler cooldownHandler) {
      CommandBuffer<EntityStore> buffer = context.getCommandBuffer();
      if (buffer == null) {
         context.getState().state = InteractionState.Failed;
      } else {
         ItemStack held = context.getHeldItem();
         if (held != null && !held.isEmpty()) {
            Ref<EntityStore> playerRef = context.getEntity();
            Entity ent = EntityUtils.getEntity(playerRef, buffer);
            if (!(ent instanceof LivingEntity)) {
               context.getState().state = InteractionState.Failed;
            } else {
               LivingEntity living = (LivingEntity)ent;
               if (!(living instanceof Player)) {
                  context.getState().state = InteractionState.Failed;
               } else {
                  Player player = (Player)living;
                  CapturedNPCMetadata meta = (CapturedNPCMetadata)held.getFromMetadataOrNull("CapturedEntity", CapturedNPCMetadata.CODEC);
                  if (meta == null) {
                     HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] RELEASE_FAIL no CapturedEntity metadata");
                     context.getState().state = InteractionState.Failed;
                  } else {
                     BlockPosition target = context.getTargetBlock();
                     if (target == null) {
                        context.getState().state = InteractionState.Failed;
                     } else {
                        Vector3d spawnPos = new Vector3d((double)target.x + 0.5D, (double)target.y + 0.5D, (double)target.z + 0.5D);
                        BlockFace face = null;
                        if (context.getClientState() != null) {
                           face = BlockFace.fromProtocolFace(context.getClientState().blockFace);
                        }

                        Vector3d finalSpawnPos;
                        if (face != null) {
                           finalSpawnPos = new Vector3d(face.getDirection());
                           spawnPos.add(finalSpawnPos);
                        }

                        finalSpawnPos = SpawnPosUtil.makeSafe(spawnPos);
                        Integer roleIndexValue = MetaReadUtil.readRoleIndex(meta);
                        if (roleIndexValue == null) {
                           HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] RELEASE_FAIL roleIndex unavailable");
                           context.getState().state = InteractionState.Failed;
                           return;
                        }

                        int roleIndex = roleIndexValue;
                        String nameKey = meta.getNpcNameKey();
                        NPCPlugin npcPlugin = NPCPlugin.get();
                        HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] RELEASE_USE roleIndex=%s npc=%s pos=%s face=%s", roleIndex, nameKey, finalSpawnPos, face == null ? "null" : face.name());
                        buffer.run((store) -> {
                           boolean spawned = spawnNpcSafe(store, npcPlugin, roleIndex, nameKey, finalSpawnPos);
                           if (!spawned) {
                              HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] RELEASE_FAIL spawnNpcSafe returned false");
                           } else {
                              boolean consumed = false;

                              try {
                                 consumed = ConsumeUtil.consumeActiveHotbarItem(player, held);
                              } catch (Throwable var10) {
                                 HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] RELEASE_FAIL consume exception=%s", String.valueOf(var10));
                              }

                              HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] RELEASE_OK spawned=true consume ok=%s", consumed);
                           }
                        });
                        context.getState().state = InteractionState.Finished;
                     }
                  }
               }
            }
         } else {
            context.getState().state = InteractionState.Failed;
         }
      }
   }

   private static boolean spawnNpcSafe(Store<EntityStore> store, NPCPlugin npcPlugin, int roleIndex, String nameKey, Vector3d pos) {
      Method m;
      try {
         m = npcPlugin.getClass().getMethod("spawnEntity", Store.class, Integer.TYPE, String.class, Vector3d.class, Vector3f.class, Model.class, TriConsumer.class);
         m.invoke(npcPlugin, store, roleIndex, nameKey, pos, Vector3f.ZERO, null, null);
         HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] RELEASE_SPAWN used signature: (Store,int,String,Vector3d,Vector3f,Model,TriConsumer)");
         return true;
      } catch (NoSuchMethodException var9) {
      } catch (Throwable var10) {
         HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] RELEASE_FAIL spawn(sig:role+name) ex=%s", String.valueOf(var10));
      }

      try {
         m = npcPlugin.getClass().getMethod("spawnEntity", Store.class, Integer.TYPE, Vector3d.class, Vector3f.class, Model.class, TriConsumer.class, Integer.TYPE);
         m.invoke(npcPlugin, store, roleIndex, pos, Vector3f.ZERO, null, null, 0);
         HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] RELEASE_SPAWN used signature: (Store,int,Vector3d,Vector3f,Model,TriConsumer,int)");
         return true;
      } catch (NoSuchMethodException var7) {
      } catch (Throwable var8) {
         HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] RELEASE_FAIL spawn(sig:+spawnCfg) ex=%s", String.valueOf(var8));
      }

      try {
         npcPlugin.spawnEntity(store, roleIndex, pos, Vector3f.ZERO, (Model)null, (TriConsumer)null);
         HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] RELEASE_SPAWN used fallback signature: (Store,int,Vector3d,Vector3f,Model,TriConsumer)");
         return true;
      } catch (Throwable var6) {
         HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] RELEASE_FAIL spawn(fallback) ex=%s", String.valueOf(var6));
         return false;
      }
   }

   static {
      CODEC = ((Builder)BuilderCodec.builder(PokeBallReleaseInteraction.class, PokeBallReleaseInteraction::new, SimpleInstantInteraction.CODEC).documentation("Release a captured NPC from a Pok\u00e9Ball (consumes the ball).")).build();
   }
}
